<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands.proto

namespace GPBMetadata;

class Commands
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5e0a0e636f6d6d616e64732e70726f746f120e686f6f6b732e636f6d6d" .
            "616e647322180a084563686f54657874120c0a0474657874180120012809" .
            "221a0a0953656e64456d61696c120d0a05656d61696c1801200128096206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

