<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands.proto

namespace GPBMetadata;

class Commands
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a440a0e636f6d6d616e64732e70726f746f120e686f6f6b732e636f6d6d" .
            "616e6473221a0a0953656e64456d61696c120d0a05656d61696c18012001" .
            "2809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

