<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace GPBMetadata;

class Events
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9c010a0c6576656e74732e70726f746f120c686f6f6b732e6576656e74" .
            "7322570a0e436f6e7461637443726561746564120c0a046e616d65180120" .
            "012809120d0a05656d61696c18022001280912280a0570686f6e65180320" .
            "03280b32192e686f6f6b732e6576656e74732e50686f6e654e756d626572" .
            "221d0a0b50686f6e654e756d626572120e0a066e756d6265721801200128" .
            "09620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

