FROM rabbitmq:3-management-alpine

RUN apk add --update --virtual .build-deps ca-certificates wget && \
	wget https://bintray.com/rabbitmq/community-plugins/download_file?file_path=rabbitmq_delayed_message_exchange-0.0.1.ez \
		-O /plugins/rabbitmq_delayed_message_exchange.ez && \
	rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange && \
	apk del .build-deps
