version: "3"
services:
  prooph-producer:
    image: php:proto
    build:
      context: devops
      dockerfile: Dockerfile.php-proto
    volumes:
      - ./prooph-producer:/app
    working_dir: /app
    ports:
      - 80:8080
    command: composer run --timeout=0 serve --dev
    links:
      - rabbitmq:rabbitmq
  prooph-consumer:
    image: php:proto
    build:
      context: devops
      dockerfile: Dockerfile.php-proto
    volumes:
      - ./prooph-consumer:/app
    working_dir: /app
    links:
      - rabbitmq:rabbitmq
    ports:
      - 8000:8080
    command: composer run --timeout=0 serve --dev
  rabbitmq:
    image: rabbitmq:3-with-delay
    build:
      context: devops
      dockerfile: Dockerfile.rabbitmq
    ports:
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
