version: "3"
services:
  without-prooph:
    image: php:proto
    build:
      context: devops
      dockerfile: Dockerfile.php-proto
    volumes:
      - ./without-prooph:/app
    working_dir: /app
  with-prooph:
    image: php:proto
    build:
      context: devops
      dockerfile: Dockerfile.php-proto
    volumes:
      - ./with-prooph:/app
    working_dir: /app
