<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands.proto

namespace Hooks\Commands;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>hooks.commands.EchoText</code>
 */
class EchoText extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string text = 1;</code>
     */
    private $text = '';

    public function __construct() {
        \GPBMetadata\Commands::initOnce();
        parent::__construct();
    }

    /**
     * <code>string text = 1;</code>
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * <code>string text = 1;</code>
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;
    }

}

