<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Hooks\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>hooks.events.ContactCreated</code>
 */
class ContactCreated extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <code>string email = 2;</code>
     */
    private $email = '';
    /**
     * <code>repeated .hooks.events.PhoneNumber phone = 3;</code>
     */
    private $phone;

    public function __construct() {
        \GPBMetadata\Events::initOnce();
        parent::__construct();
    }

    /**
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <code>string email = 2;</code>
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * <code>string email = 2;</code>
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;
    }

    /**
     * <code>repeated .hooks.events.PhoneNumber phone = 3;</code>
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * <code>repeated .hooks.events.PhoneNumber phone = 3;</code>
     */
    public function setPhone(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Hooks\Events\PhoneNumber::class);
        $this->phone = $arr;
    }

}

