<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Hooks\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>hooks.events.PhoneNumber</code>
 */
class PhoneNumber extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string number = 1;</code>
     */
    private $number = '';

    public function __construct() {
        \GPBMetadata\Events::initOnce();
        parent::__construct();
    }

    /**
     * <code>string number = 1;</code>
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * <code>string number = 1;</code>
     */
    public function setNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->number = $var;
    }

}

